version: "3.3"

services:
  nginx:
    depends_on:
      - web
      - apache
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
    restart: always

  web:
    build: ./web
    expose:
      - '3000'
    restart: always

  apache:
    build: ./apache/frontend
    ports:
      - 20080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app