version: "3.3"
# Указываем раздел со связанными сервисами

services:
  nginx:
    depends_on:
      - nuxt
    image: nginx:latest
    ports:
      - '81:81'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
    restart: always

  nuxt:
    build: ./nuxt
    expose:
      - '3000'
    restart: always